name: structure-based-admet-prediction2
channels:
  - conda-forge
  - schrodinger
dependencies:
  - ipython=8.12.0
  - jupyter=1.0.0
  - mdanalysis=2.4.3
  - numpy=1.24.2
  - openbabel=3.1.1
  - pdbfixer=1.8.1
  - prolif=1.1.0
  - py3dmol=2.0.1.post1
  - pymol=2.5.5
  - python=3.9
  - rdkit=2022.09.4
  - scikit-learn=1.2.2
  - vina=1.2.3
