name: structure-based-admet-prediction
channels:
  - conda-forge
  - schrodinger
dependencies:
  - jupyter
  - mdanalysis
  - numpy
  - openbabel
  - pdbfixer
  - prolif
  - py3dmol
  - pydantic
  - pymol
  - python=3.9
  - rdkit
  - scikit-learn
  - smina
  - typer
  - vina
